FROM rust:1.78.0 AS builder

WORKDIR /app/worker-sb

COPY Cargo.toml .

# Build the dependencies without the actual source code to cache dependencies separately
RUN cargo build --release

# Now copy the source code
COPY . .

# Build your application
RUN cargo build --release

CMD [ "cargo" "run" ]